sudo: false
cache:
  apt: true
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
addons:
  apt:
    packages:
    - aspell
    - aspell-en
language: scala
scala:
   - 2.11.6
jdk:
  - oraclejdk8
script:
  - ./sbt test
  - ./sbt test -Dorg.nlogo.is3d=true
notifications:
  email:
    - nicolaspayette@gmail.com
