cache:
  apt: true
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
addons:
  apt:
    packages:
    - aspell
    - aspell-en
language: scala
scala:
   - 2.12.8
jdk:
  - openjdk8
script:
  - pyenv global 3.6
  - python --version
  - pip install --user sklearn
  - sbt test:compile
  - sbt test
  - sbt test -Dorg.nlogo.is3d=true
  # Tricks to avoid unnecessary cache updates (see http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html)
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    - connorbain@u.northwestern.edu
